site_name: FloydHub
site_url: https://www.floydhub.com
site_author: FloydHub Team
pages:
    - Home: index.md
    - Installation: installation.md
    - Commands: commands.md
theme: flatly
extra_css:
    - css/bootstrap_paper.min.css
copyright: Copyright &copy; 2017 Floyd Labs Inc.