site_name: FloydHub
site_url: https://www.floydhub.com
site_author: FloydHub Team
repo_url: https://github.com/floydhub/floyd-docs
pages:
    - Home: index.md
    - Get Started:
        - 'Quick Start': getstarted/quick_start.md
        - 'Quick Start - Jupyter Notebook': getstarted/quick_start_jupyter.md
    - Guides:
        - 'Installation': guides/install.md
    - FAQs:
        - 'Installation FAQs': faqs/installation.md
        - 'Signup and Login FAQs': faqs/authentication.md
    - Changelogs:
        - 'July 12 2017': changelogs/1.md
theme: material
extra:
  palette:
    primary: 'blue'
    accent: 'blue'
    extra:
  logo: 'img/f_white_small.png'
  font:
    text: 'Roboto'
    code: 'Source Code Pro'
  social:
    - type: 'github'
      link: 'https://github.com/floydhub'
    - type: 'twitter'
      link: 'https://twitter.com/floydhub_'
markdown_extensions:
    - markdown_include.include:
        base_path: docs
extra_css:
    - css/bootstrap_paper.min.css
    - css/style.css
copyright: Copyright &copy; 2017 Floyd Labs Inc.
